name: .NET

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Restore
      run: dotnet restore RentalManagement.API/RentalManagement.API.sln
    - name: Build
      run: dotnet build RentalManagement.API/RentalManagement.API.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test RentalManagement.API/RentalManagement.API.sln --no-build --verbosity normal
